<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { salesOwners } from '../../mock/sales'
import { useSalesStore } from '../../stores/sales'
const route=useRoute(),store=useSalesStore(),keyword=ref(''),status=ref('all'),formVisible=ref(false),detailVisible=ref(false),paymentVisible=ref(false),planVisible=ref(false),mode=ref('create'),formRef=ref(),paymentRef=ref(),planRef=ref(),selectedId=ref(null),selectedPlan=ref(null)
const form=reactive({id:null,name:'',customerId:null,opportunityId:null,amount:0,signedAt:'',startAt:'',endAt:'',owner:'',status:'待生效'}),paymentForm=reactive({amount:0,paidDate:''}),planForm=reactive({phase:'',dueDate:'',amount:0})
const selected=computed(()=>store.contracts.find(i=>i.id===selectedId.value)), plans=computed(()=>store.paymentPlans.filter(i=>i.contractId===selectedId.value)), filtered=computed(()=>store.contracts.filter(i=>(status.value==='all'||i.status===status.value)&&(!keyword.value||`${i.name}${i.code}${store.customerMap[i.customerId]?.name}`.toLowerCase().includes(keyword.value.toLowerCase())))),summary=computed(()=>({amount:store.contracts.reduce((s,i)=>s+i.amount,0),paid:store.contracts.reduce((s,i)=>s+i.paid,0),overdue:store.contracts.filter(i=>i.status==='回款逾期').length,executing:store.contracts.filter(i=>i.status==='执行中').length}))
const rules={name:[{required:true,message:'请输入合同名称',trigger:'blur'}],customerId:[{required:true,message:'请选择客户',trigger:'change'}],amount:[{required:true,message:'请输入合同金额',trigger:'blur'}],signedAt:[{required:true,message:'请选择签订日期',trigger:'change'}],owner:[{required:true,message:'请选择负责人',trigger:'change'}]},paymentRules={amount:[{required:true,message:'请输入回款金额',trigger:'blur'}],paidDate:[{required:true,message:'请选择到账日期',trigger:'change'}]},planRules={phase:[{required:true,message:'请输入回款期次',trigger:'blur'}],dueDate:[{required:true,message:'请选择计划日期',trigger:'change'}],amount:[{required:true,message:'请输入计划金额',trigger:'blur'}]}
function reset(){Object.assign(form,{id:null,name:'',customerId:null,opportunityId:null,amount:0,signedAt:'',startAt:'',endAt:'',owner:'',status:'待生效'})}function openCreate(customerId=null){reset();form.customerId=customerId;mode.value='create';formVisible.value=true}function openEdit(i){Object.assign(form,i);mode.value='edit';formVisible.value=true}
async function save(){await formRef.value.validate();const p={...form};delete p.id;mode.value==='create'?store.addContract(p):store.updateContract(form.id,p);formVisible.value=false;ElMessage.success(mode.value==='create'?'合同已创建':'合同已更新')}
async function remove(i){try{await ElMessageBox.confirm(`确定删除合同“${i.name}”及其回款计划吗？`,'删除合同',{confirmButtonText:'确定删除',cancelButtonText:'取消',type:'warning'});store.removeContract(i.id);detailVisible.value=false;ElMessage.success('合同已删除')}catch{/* 保留合同。 */}}
function openDetail(i){selectedId.value=i.id;detailVisible.value=true}function openPlan(){Object.assign(planForm,{phase:'',dueDate:'',amount:0});planVisible.value=true}async function savePlan(){await planRef.value.validate();store.addPaymentPlan({...planForm,contractId:selectedId.value});planVisible.value=false;ElMessage.success('回款计划已添加')}
function openPayment(i){selectedPlan.value=i;Object.assign(paymentForm,{amount:Math.max(i.amount-i.paidAmount,0),paidDate:new Date().toISOString().slice(0,10)});paymentVisible.value=true}async function savePayment(){await paymentRef.value.validate();store.registerPayment(selectedPlan.value.id,paymentForm.amount,paymentForm.paidDate);paymentVisible.value=false;ElMessage.success('回款已登记，合同与客户金额已同步')}
function exportContracts(){const rows=[['合同编号','合同名称','客户','合同金额','已回款','状态'],...filtered.value.map(i=>[i.code,i.name,store.customerMap[i.customerId]?.name,i.amount,i.paid,i.status])];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([`\ufeff${rows.map(r=>r.join(',')).join('\n')}`],{type:'text/csv;charset=utf-8'}));a.download='合同回款台账.csv';a.click();URL.revokeObjectURL(a.href);ElMessage.success('合同台账已导出')}
function statusType(v){return {'执行中':'primary','回款逾期':'danger','即将到期':'warning','已完成':'success','待生效':'info'}[v]||'info'}onMounted(()=>{if(route.query.customerId)openCreate(Number(route.query.customerId))})
</script>
<template><div class="sales-page contract-page"><header class="sales-header"><div><span>CONTRACT & COLLECTION</span><h1>合同与回款</h1><p>统一跟踪销售合同履约、开票和回款计划。</p></div><div><el-button @click="exportContracts"><el-icon><Download /></el-icon>导出台账</el-button><el-button type="primary" @click="openCreate()"><el-icon><Plus /></el-icon>新建合同</el-button></div></header>
<section class="contract-ledger"><div class="ledger-total"><span>合同总额</span><strong>{{ summary.amount.toLocaleString() }}<small>万元</small></strong><p>累计 {{ store.contracts.length }} 份合同</p></div><div><span>累计回款</span><strong>{{ summary.paid.toLocaleString() }} 万元</strong><el-progress :percentage="Math.round(summary.paid/summary.amount*100)" /></div><div><span>执行中合同</span><strong>{{ summary.executing }} 份</strong><small>持续履约跟踪</small></div><div class="warning"><span>回款逾期</span><strong>{{ summary.overdue }} 份</strong><small>需要优先处理</small></div></section>
<section class="sales-table-panel"><div class="contract-toolbar"><el-input v-model="keyword" clearable placeholder="搜索合同编号、名称或客户"><template #prefix><el-icon><Search /></el-icon></template></el-input><el-select v-model="status"><el-option label="全部状态" value="all" /><el-option v-for="i in ['待生效','执行中','即将到期','回款逾期','已完成']" :key="i" :label="i" :value="i" /></el-select></div><el-table :data="filtered"><el-table-column prop="code" label="合同编号" width="120" /><el-table-column prop="name" label="合同名称" min-width="230" /><el-table-column label="客户" min-width="150"><template #default="{row}">{{store.customerMap[row.customerId]?.shortName}}</template></el-table-column><el-table-column label="合同金额" width="100"><template #default="{row}">{{row.amount}} 万</template></el-table-column><el-table-column label="回款进度" min-width="160"><template #default="{row}"><span>{{row.paid}} / {{row.amount}} 万</span><el-progress :percentage="Math.round(row.paid/row.amount*100)" :stroke-width="6" /></template></el-table-column><el-table-column prop="endAt" label="到期日期" width="108" /><el-table-column label="状态" width="95"><template #default="{row}"><el-tag :type="statusType(row.status)">{{row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="155" fixed="right"><template #default="{row}"><el-button link type="primary" @click="openDetail(row)">查看</el-button><el-button link @click="openEdit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table></section>
<el-drawer v-model="detailVisible" title="合同履约详情" size="600px"><div v-if="selected" class="contract-detail"><div class="contract-detail-head"><div><span>{{selected.code}}</span><h2>{{selected.name}}</h2><p>{{store.customerMap[selected.customerId]?.name}}</p></div><el-tag :type="statusType(selected.status)">{{selected.status}}</el-tag></div><div class="contract-amount"><div><span>合同金额</span><strong>{{selected.amount}} 万</strong></div><div><span>已开票</span><strong>{{selected.invoiced}} 万</strong></div><div><span>已回款</span><strong>{{selected.paid}} 万</strong></div></div><el-steps :active="selected.status==='已完成'?4:2" finish-status="success"><el-step title="合同签订" :description="selected.signedAt" /><el-step title="合同生效" :description="selected.startAt" /><el-step title="履约执行" description="当前阶段" /><el-step title="合同完成" :description="selected.endAt" /></el-steps><div class="payment-head"><div><h3>回款计划</h3><p>按合同约定登记计划与实际到账</p></div><el-button type="primary" plain @click="openPlan"><el-icon><Plus /></el-icon>添加计划</el-button></div><div class="payment-list"><article v-for="i in plans" :key="i.id"><div><strong>{{i.phase}}</strong><span>计划 {{i.dueDate}}</span></div><div><span>{{i.paidAmount}} / {{i.amount}} 万</span><el-progress :percentage="Math.round(i.paidAmount/i.amount*100)" :stroke-width="6" /></div><el-tag :type="i.status==='已回款'?'success':i.status==='逾期'?'danger':'warning'">{{i.status}}</el-tag><el-button size="small" :disabled="i.paidAmount>=i.amount" @click="openPayment(i)">登记回款</el-button></article></div></div></el-drawer>
<el-dialog v-model="formVisible" :title="mode==='create'?'新建销售合同':'编辑销售合同'" width="700px"><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><el-form-item label="合同名称" prop="name"><el-input v-model="form.name" /></el-form-item><div class="sales-form-grid"><el-form-item label="签约客户" prop="customerId"><el-select v-model="form.customerId" filterable style="width:100%"><el-option v-for="i in store.customers" :key="i.id" :label="i.name" :value="i.id" /></el-select></el-form-item><el-form-item label="来源商机"><el-select v-model="form.opportunityId" clearable style="width:100%"><el-option v-for="i in store.opportunities.filter(i=>i.customerId===form.customerId)" :key="i.id" :label="i.name" :value="i.id" /></el-select></el-form-item><el-form-item label="合同金额（万元）" prop="amount"><el-input-number v-model="form.amount" :min="0" style="width:100%" /></el-form-item><el-form-item label="负责人" prop="owner"><el-select v-model="form.owner" style="width:100%"><el-option v-for="i in salesOwners" :key="i" :label="i" :value="i" /></el-select></el-form-item><el-form-item label="签订日期" prop="signedAt"><el-date-picker v-model="form.signedAt" value-format="YYYY-MM-DD" type="date" style="width:100%" /></el-form-item><el-form-item label="合同状态"><el-select v-model="form.status" style="width:100%"><el-option v-for="i in ['待生效','执行中','即将到期','回款逾期','已完成']" :key="i" :label="i" :value="i" /></el-select></el-form-item><el-form-item label="开始日期"><el-date-picker v-model="form.startAt" value-format="YYYY-MM-DD" type="date" style="width:100%" /></el-form-item><el-form-item label="结束日期"><el-date-picker v-model="form.endAt" value-format="YYYY-MM-DD" type="date" style="width:100%" /></el-form-item></div></el-form><template #footer><el-button @click="formVisible=false">取消</el-button><el-button type="primary" @click="save">保存合同</el-button></template></el-dialog>
<el-dialog v-model="planVisible" title="添加回款计划" width="500px"><el-form ref="planRef" :model="planForm" :rules="planRules" label-position="top"><el-form-item label="回款期次" prop="phase"><el-input v-model="planForm.phase" /></el-form-item><el-form-item label="计划日期" prop="dueDate"><el-date-picker v-model="planForm.dueDate" value-format="YYYY-MM-DD" type="date" style="width:100%" /></el-form-item><el-form-item label="计划金额（万元）" prop="amount"><el-input-number v-model="planForm.amount" :min="0" style="width:100%" /></el-form-item></el-form><template #footer><el-button @click="planVisible=false">取消</el-button><el-button type="primary" @click="savePlan">保存计划</el-button></template></el-dialog>
<el-dialog v-model="paymentVisible" title="登记实际回款" width="480px"><el-form ref="paymentRef" :model="paymentForm" :rules="paymentRules" label-position="top"><el-alert :title="`${selectedPlan?.phase||''} · 尚待回款 ${(selectedPlan?.amount||0)-(selectedPlan?.paidAmount||0)} 万元`" type="info" :closable="false" /><el-form-item label="本次到账金额（万元）" prop="amount"><el-input-number v-model="paymentForm.amount" :min="0.01" style="width:100%" /></el-form-item><el-form-item label="到账日期" prop="paidDate"><el-date-picker v-model="paymentForm.paidDate" value-format="YYYY-MM-DD" type="date" style="width:100%" /></el-form-item></el-form><template #footer><el-button @click="paymentVisible=false">取消</el-button><el-button type="primary" @click="savePayment">确认到账</el-button></template></el-dialog></div></template>
