<script setup>
import { computed, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { customerIndustries, customerLevels, salesOwners } from '../../mock/sales'
import { useSalesStore } from '../../stores/sales'

const router = useRouter(), store = useSalesStore()
const keyword = ref(''), level = ref('all'), industry = ref('all'), status = ref('all'), region = ref('all')
const selectedRows = ref([]), formVisible = ref(false), assignVisible = ref(false), mode = ref('create'), formRef = ref(), assignedOwner = ref('')
const form = reactive({ id: null, name: '', shortName: '', industry: '', region: '华东', level: '普通客户', owner: '', status: '意向', address: '', scale: '200—499 人', source: '', tags: [] })
const rules = { name: [{ required: true, message: '请输入客户名称', trigger: 'blur' }], shortName: [{ required: true, message: '请输入客户简称', trigger: 'blur' }], industry: [{ required: true, message: '请选择行业', trigger: 'change' }], owner: [{ required: true, message: '请选择负责人', trigger: 'change' }] }
const filtered = computed(() => store.customers.filter((item) => (!keyword.value || `${item.name}${item.code}${item.owner}`.toLowerCase().includes(keyword.value.toLowerCase())) && (level.value === 'all' || item.level === level.value) && (industry.value === 'all' || item.industry === industry.value) && (status.value === 'all' || item.status === status.value) && (region.value === 'all' || item.region === region.value)))
const summary = computed(() => ({ total: store.customers.length, strategic: store.customers.filter((item) => item.level === '战略客户').length, active: store.customers.filter((item) => item.status === '合作中').length, amount: store.customers.reduce((sum, item) => sum + item.contractAmount, 0) }))

function resetForm() { Object.assign(form, { id: null, name: '', shortName: '', industry: '', region: '华东', level: '普通客户', owner: '', status: '意向', address: '', scale: '200—499 人', source: '', tags: [] }) }
function openCreate() { resetForm(); mode.value = 'create'; formVisible.value = true }
function openEdit(row) { Object.assign(form, JSON.parse(JSON.stringify(row))); mode.value = 'edit'; formVisible.value = true }
async function save() { await formRef.value.validate(); const payload = { ...form }; delete payload.id; mode.value === 'create' ? store.addCustomer(payload) : store.updateCustomer(form.id, payload); formVisible.value = false; ElMessage.success(mode.value === 'create' ? '客户已新增' : '客户资料已更新') }
async function remove(row) { try { await ElMessageBox.confirm(`删除“${row.name}”将同时移除其联系人、商机和合同数据，确定继续吗？`, '删除客户', { confirmButtonText: '确定删除', cancelButtonText: '取消', type: 'warning' }); store.removeCustomer(row.id); ElMessage.success('客户已删除') } catch { /* 保留客户。 */ } }
function openAssign() { if (!selectedRows.value.length) return; assignedOwner.value = ''; assignVisible.value = true }
function saveAssign() { if (!assignedOwner.value) { ElMessage.warning('请选择负责人'); return }; selectedRows.value.forEach((item) => store.updateCustomer(item.id, { owner: assignedOwner.value })); assignVisible.value = false; selectedRows.value = []; ElMessage.success('客户负责人已批量更新') }
function exportCustomers() { const rows = [['客户编号','客户名称','行业','区域','等级','负责人','合同金额','已回款','状态'], ...filtered.value.map((i) => [i.code,i.name,i.industry,i.region,i.level,i.owner,i.contractAmount,i.paidAmount,i.status])]; const link=document.createElement('a'); link.href=URL.createObjectURL(new Blob([`\ufeff${rows.map((r)=>r.join(',')).join('\n')}`],{type:'text/csv;charset=utf-8'})); link.download='客户台账.csv'; link.click(); URL.revokeObjectURL(link.href); ElMessage.success('客户台账已导出') }
function levelType(value) { return { 战略客户: 'danger', 重点客户: 'warning', 普通客户: 'primary', 潜在客户: 'info' }[value] }
</script>

<template><div class="sales-page customer-list-page">
  <header class="sales-header"><div><span>CUSTOMER MANAGEMENT</span><h1>客户管理</h1><p>集中维护客户资产、合作状态和销售责任关系。</p></div><div><el-button @click="exportCustomers"><el-icon><Download /></el-icon>导出客户</el-button><el-button type="primary" @click="openCreate"><el-icon><Plus /></el-icon>新增客户</el-button></div></header>
  <section class="customer-summary"><div><span>客户总数</span><strong>{{ summary.total }}</strong><small>家企业客户</small></div><div><span>战略客户</span><strong>{{ summary.strategic }}</strong><small>重点资源投入</small></div><div><span>合作中客户</span><strong>{{ summary.active }}</strong><small>持续业务往来</small></div><div class="wide"><span>累计合同金额</span><strong>{{ summary.amount.toLocaleString() }}<em>万元</em></strong><el-progress :percentage="78" :show-text="false" /></div></section>
  <div class="customer-layout"><aside class="customer-filter-side"><h3>客户分类</h3><button :class="{active:level==='all'}" @click="level='all'"><span>全部客户</span><b>{{ store.customers.length }}</b></button><button v-for="item in customerLevels" :key="item" :class="{active:level===item}" @click="level=item"><span>{{ item }}</span><b>{{ store.customers.filter((row)=>row.level===item).length }}</b></button><div class="filter-divider"></div><h3>所在区域</h3><el-radio-group v-model="region"><el-radio value="all">全部区域</el-radio><el-radio value="华东">华东</el-radio><el-radio value="华南">华南</el-radio><el-radio value="华北">华北</el-radio><el-radio value="西部">西部</el-radio></el-radio-group></aside>
  <main class="customer-table-panel"><div class="customer-toolbar"><el-input v-model="keyword" clearable placeholder="搜索客户名称、编号或负责人"><template #prefix><el-icon><Search /></el-icon></template></el-input><el-select v-model="industry"><el-option label="全部行业" value="all" /><el-option v-for="item in customerIndustries" :key="item" :label="item" :value="item" /></el-select><el-select v-model="status"><el-option label="全部状态" value="all" /><el-option label="合作中" value="合作中" /><el-option label="意向" value="意向" /><el-option label="沉默" value="沉默" /></el-select><el-button :disabled="!selectedRows.length" @click="openAssign">批量分配</el-button></div>
  <el-table :data="filtered" @selection-change="selectedRows=$event"><el-table-column type="selection" width="45" /><el-table-column label="客户" min-width="215"><template #default="{row}"><button class="customer-name" @click="router.push(`/sales/customers/${row.id}`)"><span>{{ row.shortName.slice(0,2) }}</span><div><strong>{{ row.name }}</strong><small>{{ row.code }}</small></div></button></template></el-table-column><el-table-column prop="industry" label="行业" width="90" /><el-table-column prop="region" label="区域" width="70" /><el-table-column label="等级" width="95"><template #default="{row}"><el-tag :type="levelType(row.level)" size="small">{{ row.level }}</el-tag></template></el-table-column><el-table-column prop="owner" label="负责人" width="85" /><el-table-column label="合同 / 回款" min-width="145"><template #default="{row}"><div class="amount-cell"><strong>{{ row.contractAmount }} 万</strong><span>已回款 {{ row.paidAmount }} 万</span></div></template></el-table-column><el-table-column prop="lastFollowUp" label="最近跟进" width="105" /><el-table-column prop="status" label="状态" width="75" /><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button link type="primary" @click="router.push(`/sales/customers/${row.id}`)">查看</el-button><el-button link @click="openEdit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><el-empty v-if="!filtered.length" description="没有符合条件的客户" /></main></div>
  <el-dialog v-model="formVisible" :title="mode==='create'?'新增客户':'编辑客户'" width="700px"><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><div class="sales-form-grid"><el-form-item label="客户全称" prop="name" class="span-two"><el-input v-model="form.name" /></el-form-item><el-form-item label="客户简称" prop="shortName"><el-input v-model="form.shortName" /></el-form-item><el-form-item label="所属行业" prop="industry"><el-select v-model="form.industry" style="width:100%"><el-option v-for="item in customerIndustries" :key="item" :label="item" :value="item" /></el-select></el-form-item><el-form-item label="所在区域"><el-select v-model="form.region" style="width:100%"><el-option v-for="item in ['华东','华南','华北','西部','海外']" :key="item" :label="item" :value="item" /></el-select></el-form-item><el-form-item label="客户等级"><el-select v-model="form.level" style="width:100%"><el-option v-for="item in customerLevels" :key="item" :label="item" :value="item" /></el-select></el-form-item><el-form-item label="负责人" prop="owner"><el-select v-model="form.owner" style="width:100%"><el-option v-for="item in salesOwners" :key="item" :label="item" :value="item" /></el-select></el-form-item><el-form-item label="合作状态"><el-select v-model="form.status" style="width:100%"><el-option label="意向" value="意向" /><el-option label="合作中" value="合作中" /><el-option label="沉默" value="沉默" /></el-select></el-form-item><el-form-item label="企业规模"><el-input v-model="form.scale" /></el-form-item><el-form-item label="客户来源"><el-input v-model="form.source" /></el-form-item><el-form-item label="详细地址" class="span-two"><el-input v-model="form.address" /></el-form-item></div></el-form><template #footer><el-button @click="formVisible=false">取消</el-button><el-button type="primary" @click="save">保存客户</el-button></template></el-dialog>
  <el-dialog v-model="assignVisible" title="批量分配负责人" width="430px"><p>已选择 {{ selectedRows.length }} 家客户</p><el-select v-model="assignedOwner" placeholder="请选择负责人" style="width:100%"><el-option v-for="item in salesOwners" :key="item" :label="item" :value="item" /></el-select><template #footer><el-button @click="assignVisible=false">取消</el-button><el-button type="primary" @click="saveAssign">确认分配</el-button></template></el-dialog>
</div></template>
