<script setup>
import { computed, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useSalesStore } from '../../stores/sales'

const route=useRoute(), router=useRouter(), store=useSalesStore(), customerId=computed(()=>Number(route.params.id))
const customer=computed(()=>store.customers.find((item)=>item.id===customerId.value)), contacts=computed(()=>store.contacts.filter((i)=>i.customerId===customerId.value)), followUps=computed(()=>store.followUps.filter((i)=>i.customerId===customerId.value)), opportunities=computed(()=>store.opportunities.filter((i)=>i.customerId===customerId.value)), contracts=computed(()=>store.contracts.filter((i)=>i.customerId===customerId.value))
const activeTab=ref('followups'), contactVisible=ref(false), followVisible=ref(false), contactMode=ref('create'), contactRef=ref(), followRef=ref()
const contactForm=reactive({id:null,name:'',position:'',mobile:'',email:'',role:'影响人',primary:false}), followForm=reactive({type:'电话',content:'',owner:'',nextDate:''})
const contactRules={name:[{required:true,message:'请输入联系人姓名',trigger:'blur'}],mobile:[{required:true,message:'请输入联系电话',trigger:'blur'}]}, followRules={content:[{required:true,message:'请输入跟进内容',trigger:'blur'}],owner:[{required:true,message:'请输入跟进人',trigger:'blur'}],nextDate:[{required:true,message:'请选择下次跟进日期',trigger:'change'}]}
function openContact(item=null){Object.assign(contactForm,item?{...item}:{id:null,name:'',position:'',mobile:'',email:'',role:'影响人',primary:false});contactMode.value=item?'edit':'create';contactVisible.value=true}
async function saveContact(){await contactRef.value.validate();const payload={...contactForm,customerId:customerId.value};delete payload.id;contactMode.value==='create'?store.addContact(payload):store.updateContact(contactForm.id,payload);contactVisible.value=false;ElMessage.success(contactMode.value==='create'?'联系人已添加':'联系人已更新')}
async function removeContact(item){try{await ElMessageBox.confirm(`确定删除联系人“${item.name}”吗？`,'删除联系人',{confirmButtonText:'确定删除',cancelButtonText:'取消',type:'warning'});store.removeContact(item.id);ElMessage.success('联系人已删除')}catch{/* 保留联系人。 */}}
function openFollow(){Object.assign(followForm,{type:'电话',content:'',owner:customer.value?.owner||'',nextDate:''});followVisible.value=true}
async function saveFollow(){await followRef.value.validate();store.addFollowUp({...followForm,customerId:customerId.value});followVisible.value=false;activeTab.value='followups';ElMessage.success('跟进记录已保存')}
function contactAction(type,item){ElMessage.success(`${type==='phone'?'已调起拨号':'已创建邮件'}：${type==='phone'?item.mobile:item.email}`)}
function creditType(value){return value==='良好'?'success':value==='关注'?'warning':'info'}
</script>
<template><div v-if="customer" class="sales-page customer-detail-page">
  <div class="detail-back"><el-button link @click="router.push('/sales/customers')"><el-icon><ArrowLeft /></el-icon>返回客户列表</el-button></div>
  <section class="customer-hero"><div class="customer-avatar">{{ customer.shortName.slice(0,2) }}</div><div class="customer-identity"><div><h1>{{ customer.name }}</h1><el-tag type="danger">{{ customer.level }}</el-tag><el-tag :type="creditType(customer.credit)">信用{{ customer.credit }}</el-tag></div><p>{{ customer.code }} · {{ customer.industry }} · {{ customer.region }}</p><div><span><el-icon><User /></el-icon>负责人 {{ customer.owner }}</span><span><el-icon><Location /></el-icon>{{ customer.address }}</span></div></div><div class="customer-hero-actions"><el-button @click="openFollow"><el-icon><ChatLineSquare /></el-icon>新增跟进</el-button><el-button @click="router.push({path:'/sales/opportunities',query:{customerId:customer.id}})"><el-icon><Opportunity /></el-icon>创建商机</el-button><el-button type="primary" @click="router.push({path:'/sales/contracts',query:{customerId:customer.id}})"><el-icon><DocumentAdd /></el-icon>创建合同</el-button></div></section>
  <section class="customer-finance-strip"><div><span>累计合同</span><strong>{{ customer.contractAmount }} 万元</strong></div><div><span>累计回款</span><strong>{{ customer.paidAmount }} 万元</strong></div><div><span>回款比例</span><strong>{{ customer.contractAmount?Math.round(customer.paidAmount/customer.contractAmount*100):0 }}%</strong></div><div><span>有效商机</span><strong>{{ opportunities.filter((i)=>!['赢单','输单'].includes(i.stage)).length }} 项</strong></div><div><span>最近跟进</span><strong>{{ customer.lastFollowUp||'暂无记录' }}</strong></div></section>
  <div class="customer-detail-grid"><aside class="customer-profile"><div class="side-title"><h3>客户档案</h3></div><dl><div><dt>企业简称</dt><dd>{{ customer.shortName }}</dd></div><div><dt>企业规模</dt><dd>{{ customer.scale }}</dd></div><div><dt>客户来源</dt><dd>{{ customer.source }}</dd></div><div><dt>合作状态</dt><dd>{{ customer.status }}</dd></div><div><dt>建档日期</dt><dd>{{ customer.createdAt }}</dd></div></dl><div class="customer-tags"><div class="customer-tags-head"><div><span class="customer-tags-icon"><el-icon><PriceTag /></el-icon></span><strong>客户标签</strong></div><em>{{ customer.tags.length }} 项</em></div><div class="customer-tag-list"><span v-for="tag in customer.tags" :key="tag" class="customer-tag-chip"><i></i>{{ tag }}</span></div></div></aside>
  <main class="customer-business"><el-tabs v-model="activeTab"><el-tab-pane :label="`跟进动态 ${followUps.length}`" name="followups"><div class="follow-timeline"><article v-for="item in followUps" :key="item.id"><div class="follow-dot"><el-icon><ChatDotRound /></el-icon></div><div><header><strong>{{ item.type }}跟进</strong><span>{{ item.date }}</span></header><p>{{ item.content }}</p><footer><span>跟进人：{{ item.owner }}</span><span>下次跟进：{{ item.nextDate }}</span></footer></div></article><el-empty v-if="!followUps.length" description="暂无跟进记录" /></div></el-tab-pane>
  <el-tab-pane :label="`联系人 ${contacts.length}`" name="contacts"><div class="tab-action"><el-button type="primary" @click="openContact()"><el-icon><Plus /></el-icon>新增联系人</el-button></div><el-table :data="contacts"><el-table-column prop="name" label="姓名" /><el-table-column prop="position" label="职务" /><el-table-column prop="role" label="决策角色" /><el-table-column prop="mobile" label="手机" /><el-table-column prop="email" label="邮箱" min-width="180" /><el-table-column label="操作" width="190"><template #default="{row}"><el-button link type="primary" @click="contactAction('phone',row)">拨号</el-button><el-button link @click="contactAction('email',row)">邮件</el-button><el-button link @click="openContact(row)">编辑</el-button><el-button link type="danger" @click="removeContact(row)">删除</el-button></template></el-table-column></el-table></el-tab-pane>
  <el-tab-pane :label="`商机 ${opportunities.length}`" name="opportunities"><el-table :data="opportunities"><el-table-column prop="name" label="商机名称" min-width="210" /><el-table-column prop="stage" label="阶段" /><el-table-column label="金额"><template #default="{row}">{{ row.amount }} 万</template></el-table-column><el-table-column label="赢单概率"><template #default="{row}">{{ row.probability }}%</template></el-table-column><el-table-column prop="expectedDate" label="预计签约" /></el-table></el-tab-pane>
  <el-tab-pane :label="`合同 ${contracts.length}`" name="contracts"><el-table :data="contracts"><el-table-column prop="code" label="合同编号" /><el-table-column prop="name" label="合同名称" min-width="220" /><el-table-column label="合同金额"><template #default="{row}">{{ row.amount }} 万</template></el-table-column><el-table-column label="已回款"><template #default="{row}">{{ row.paid }} 万</template></el-table-column><el-table-column prop="status" label="状态" /></el-table></el-tab-pane></el-tabs></main></div>
  <el-dialog v-model="contactVisible" :title="contactMode==='create'?'新增联系人':'编辑联系人'" width="560px"><el-form ref="contactRef" :model="contactForm" :rules="contactRules" label-position="top"><div class="sales-form-grid"><el-form-item label="姓名" prop="name"><el-input v-model="contactForm.name" /></el-form-item><el-form-item label="职务"><el-input v-model="contactForm.position" /></el-form-item><el-form-item label="手机" prop="mobile"><el-input v-model="contactForm.mobile" /></el-form-item><el-form-item label="邮箱"><el-input v-model="contactForm.email" /></el-form-item><el-form-item label="决策角色"><el-select v-model="contactForm.role" style="width:100%"><el-option label="决策人" value="决策人" /><el-option label="影响人" value="影响人" /><el-option label="使用人" value="使用人" /></el-select></el-form-item><el-form-item label="主要联系人"><el-switch v-model="contactForm.primary" /></el-form-item></div></el-form><template #footer><el-button @click="contactVisible=false">取消</el-button><el-button type="primary" @click="saveContact">保存联系人</el-button></template></el-dialog>
  <el-dialog v-model="followVisible" title="新增客户跟进" width="580px"><el-form ref="followRef" :model="followForm" :rules="followRules" label-position="top"><div class="sales-form-grid"><el-form-item label="跟进方式"><el-select v-model="followForm.type" style="width:100%"><el-option v-for="item in ['电话','会议','拜访','邮件']" :key="item" :label="item" :value="item" /></el-select></el-form-item><el-form-item label="跟进人" prop="owner"><el-input v-model="followForm.owner" /></el-form-item><el-form-item label="跟进内容" prop="content" class="span-two"><el-input v-model="followForm.content" type="textarea" :rows="4" /></el-form-item><el-form-item label="下次跟进日期" prop="nextDate"><el-date-picker v-model="followForm.nextDate" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item></div></el-form><template #footer><el-button @click="followVisible=false">取消</el-button><el-button type="primary" @click="saveFollow">保存跟进</el-button></template></el-dialog>
</div><el-result v-else icon="warning" title="未找到客户" sub-title="该客户可能已被删除"><template #extra><el-button type="primary" @click="router.push('/sales/customers')">返回客户列表</el-button></template></el-result></template>
