<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import BaseChart from '../../components/charts/BaseChart.vue'
import { opportunityStages, salesOwners } from '../../mock/sales'
import { useSalesStore } from '../../stores/sales'
const route=useRoute(),store=useSalesStore(),view=ref('board'),owner=ref('all'),keyword=ref(''),formVisible=ref(false),detailVisible=ref(false),mode=ref('create'),formRef=ref(),selected=ref(null),draggingId=ref(null)
const form=reactive({id:null,name:'',customerId:null,amount:0,stage:'初步接洽',probability:20,owner:'',expectedDate:'',nextAction:''}), rules={name:[{required:true,message:'请输入商机名称',trigger:'blur'}],customerId:[{required:true,message:'请选择客户',trigger:'change'}],owner:[{required:true,message:'请选择负责人',trigger:'change'}],expectedDate:[{required:true,message:'请选择预计签约日期',trigger:'change'}]}
const filtered=computed(()=>store.opportunities.filter(i=>(owner.value==='all'||i.owner===owner.value)&&(!keyword.value||`${i.name}${store.customerMap[i.customerId]?.name}${i.code}`.toLowerCase().includes(keyword.value.toLowerCase()))))
const activeStages=opportunityStages.filter(i=>!['输单'].includes(i)), totalAmount=computed(()=>filtered.value.filter(i=>!['输单'].includes(i.stage)).reduce((s,i)=>s+i.amount,0))
const funnelOption=computed(()=>({color:['#246bfd'],tooltip:{trigger:'axis'},grid:{left:80,right:30,top:25,bottom:25},xAxis:{type:'value',splitLine:{lineStyle:{color:'#edf1f6',type:'dashed'}}},yAxis:{type:'category',data:activeStages.map(s=>s),axisLine:{show:false},axisTick:{show:false}},series:[{type:'bar',barWidth:22,data:activeStages.map(s=>filtered.value.filter(i=>i.stage===s).reduce((n,i)=>n+i.amount,0)),itemStyle:{borderRadius:[0,7,7,0],color:'#246bfd'}}]}))
function reset(){Object.assign(form,{id:null,name:'',customerId:null,amount:0,stage:'初步接洽',probability:20,owner:'',expectedDate:'',nextAction:''})}
function openCreate(customerId=null){reset();form.customerId=customerId;mode.value='create';formVisible.value=true}
function openEdit(i){Object.assign(form,i);mode.value='edit';formVisible.value=true}
async function save(){await formRef.value.validate();const p={...form};delete p.id;mode.value==='create'?store.addOpportunity(p):store.updateOpportunity(form.id,p);formVisible.value=false;ElMessage.success(mode.value==='create'?'商机已创建':'商机已更新')}
async function remove(i){try{await ElMessageBox.confirm(`确定删除商机“${i.name}”吗？`,'删除商机',{confirmButtonText:'确定删除',cancelButtonText:'取消',type:'warning'});store.removeOpportunity(i.id);detailVisible.value=false;ElMessage.success('商机已删除')}catch{/* 保留商机。 */}}
function openDetail(i){selected.value=i;detailVisible.value=true}
function drop(stage){if(draggingId.value){store.changeOpportunityStage(draggingId.value,stage);ElMessage.success(`商机已移动至“${stage}”阶段`);draggingId.value=null}}
function stageProbability(){form.probability={初步接洽:20,需求确认:35,方案沟通:55,商务谈判:75,合同审批:90,赢单:100,输单:0}[form.stage]}
onMounted(()=>{if(route.query.customerId)openCreate(Number(route.query.customerId))})
</script>
<template><div class="sales-page opportunity-page"><header class="sales-header"><div><span>SALES PIPELINE</span><h1>商机管理</h1><p>跟踪销售机会阶段、预计金额和下一步行动。</p></div><div><el-radio-group v-model="view"><el-radio-button value="board">看板</el-radio-button><el-radio-button value="table">列表</el-radio-button><el-radio-button value="funnel">漏斗</el-radio-button></el-radio-group><el-button type="primary" @click="openCreate()"><el-icon><Plus /></el-icon>新增商机</el-button></div></header>
<section class="pipeline-summary"><div><span>有效商机</span><strong>{{ filtered.filter(i=>!['赢单','输单'].includes(i.stage)).length }} 项</strong></div><div><span>预计金额</span><strong>{{ totalAmount.toLocaleString() }} 万元</strong></div><div><span>本月高意向</span><strong>{{ filtered.filter(i=>i.probability>=75&&!['赢单','输单'].includes(i.stage)).length }} 项</strong></div><div class="pipeline-filter"><el-input v-model="keyword" clearable placeholder="搜索商机或客户"><template #prefix><el-icon><Search /></el-icon></template></el-input><el-select v-model="owner"><el-option label="全部负责人" value="all" /><el-option v-for="i in salesOwners" :key="i" :label="i" :value="i" /></el-select></div></section>
<div v-if="view==='board'" class="opportunity-board"><section v-for="stage in activeStages" :key="stage" class="stage-column" @dragover.prevent @drop="drop(stage)"><header><div><strong>{{ stage }}</strong><span>{{ filtered.filter(i=>i.stage===stage).length }}</span></div><b>{{ filtered.filter(i=>i.stage===stage).reduce((s,i)=>s+i.amount,0) }} 万</b></header><div class="stage-cards"><article v-for="item in filtered.filter(i=>i.stage===stage)" :key="item.id" draggable="true" @dragstart="draggingId=item.id" @click="openDetail(item)"><span>{{ item.code }}</span><h3>{{ item.name }}</h3><p>{{ store.customerMap[item.customerId]?.shortName }}</p><div class="opportunity-value"><strong>{{ item.amount }} 万</strong><em>{{ item.probability }}%</em></div><footer><span>{{ item.owner }}</span><span>{{ item.expectedDate.slice(5) }}</span></footer></article></div></section></div>
<section v-else-if="view==='table'" class="sales-table-panel"><el-table :data="filtered"><el-table-column prop="code" label="商机编号" width="115" /><el-table-column prop="name" label="商机名称" min-width="220" /><el-table-column label="客户" min-width="150"><template #default="{row}">{{ store.customerMap[row.customerId]?.shortName }}</template></el-table-column><el-table-column prop="stage" label="阶段" /><el-table-column label="预计金额"><template #default="{row}">{{ row.amount }} 万</template></el-table-column><el-table-column label="概率"><template #default="{row}">{{ row.probability }}%</template></el-table-column><el-table-column prop="owner" label="负责人" /><el-table-column prop="expectedDate" label="预计签约" /><el-table-column label="操作" width="130"><template #default="{row}"><el-button link type="primary" @click="openDetail(row)">查看</el-button><el-button link @click="openEdit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table></section>
<section v-else class="funnel-view"><div><h2>商机金额漏斗</h2><p>各销售阶段当前预计金额</p></div><BaseChart :option="funnelOption" height="430px" /><aside><span>整体转化率</span><strong>36.8%</strong><p>当前合同审批阶段共 {{ filtered.filter(i=>i.stage==='合同审批').length }} 项，预计金额 {{ filtered.filter(i=>i.stage==='合同审批').reduce((s,i)=>s+i.amount,0) }} 万元。</p></aside></section>
<el-dialog v-model="formVisible" :title="mode==='create'?'新增商机':'编辑商机'" width="680px"><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><el-form-item label="商机名称" prop="name"><el-input v-model="form.name" /></el-form-item><div class="sales-form-grid"><el-form-item label="客户" prop="customerId"><el-select v-model="form.customerId" filterable style="width:100%"><el-option v-for="i in store.customers" :key="i.id" :label="i.name" :value="i.id" /></el-select></el-form-item><el-form-item label="负责人" prop="owner"><el-select v-model="form.owner" style="width:100%"><el-option v-for="i in salesOwners" :key="i" :label="i" :value="i" /></el-select></el-form-item><el-form-item label="预计金额"><el-input-number v-model="form.amount" :min="0" style="width:100%" /></el-form-item><el-form-item label="销售阶段"><el-select v-model="form.stage" style="width:100%" @change="stageProbability"><el-option v-for="i in opportunityStages" :key="i" :label="i" :value="i" /></el-select></el-form-item><el-form-item label="赢单概率"><el-slider v-model="form.probability" show-input /></el-form-item><el-form-item label="预计签约" prop="expectedDate"><el-date-picker v-model="form.expectedDate" value-format="YYYY-MM-DD" type="date" style="width:100%" /></el-form-item><el-form-item label="下一步行动" class="span-two"><el-input v-model="form.nextAction" /></el-form-item></div></el-form><template #footer><el-button @click="formVisible=false">取消</el-button><el-button type="primary" @click="save">保存商机</el-button></template></el-dialog>
<el-drawer v-model="detailVisible" title="商机详情" size="470px"><div v-if="selected" class="opportunity-detail"><el-tag>{{ selected.stage }}</el-tag><h2>{{ selected.name }}</h2><p>{{ selected.code }}</p><div class="probability-ring"><el-progress type="dashboard" :percentage="selected.probability" /><span>赢单概率</span></div><el-descriptions :column="1" border><el-descriptions-item label="客户">{{ store.customerMap[selected.customerId]?.name }}</el-descriptions-item><el-descriptions-item label="预计金额">{{ selected.amount }} 万元</el-descriptions-item><el-descriptions-item label="负责人">{{ selected.owner }}</el-descriptions-item><el-descriptions-item label="预计签约">{{ selected.expectedDate }}</el-descriptions-item><el-descriptions-item label="下一步行动">{{ selected.nextAction }}</el-descriptions-item></el-descriptions><div><el-button @click="openEdit(selected);detailVisible=false">编辑商机</el-button><el-button type="danger" plain @click="remove(selected)">删除商机</el-button></div></div></el-drawer></div></template>
