<script setup>
import { computed, ref } from 'vue'
import { ElMessage } from 'element-plus'
import BaseChart from '../../components/charts/BaseChart.vue'
import { customerIndustries, salesTeamPerformance, salesTrend } from '../../mock/sales'
import { useSalesStore } from '../../stores/sales'
const store=useSalesStore(),period=ref('year'),region=ref('all'),industry=ref('all'),memberVisible=ref(false),selectedMember=ref(null)
const factor=computed(()=>period.value==='year'?1:period.value==='quarter'?0.29:0.1)
const scopedCustomers=computed(()=>store.customers.filter(i=>(region.value==='all'||i.region===region.value)&&(industry.value==='all'||i.industry===industry.value)))
const scopedIds=computed(()=>new Set(scopedCustomers.value.map(i=>i.id))), scopedContracts=computed(()=>store.contracts.filter(i=>scopedIds.value.has(i.customerId))), scopedOpps=computed(()=>store.opportunities.filter(i=>scopedIds.value.has(i.customerId)))
const totals=computed(()=>({signed:Math.round(scopedContracts.value.reduce((s,i)=>s+i.amount,0)*factor.value),paid:Math.round(scopedContracts.value.reduce((s,i)=>s+i.paid,0)*factor.value),customers:scopedCustomers.value.length,forecast:Math.round(scopedOpps.value.filter(i=>!['赢单','输单'].includes(i.stage)).reduce((s,i)=>s+i.amount*i.probability/100,0))}))
const trendOption=computed(()=>({color:['#246bfd','#30bea5'],tooltip:{trigger:'axis'},legend:{right:8},grid:{left:50,right:20,top:45,bottom:30},xAxis:{type:'category',data:salesTrend.months,axisTick:{show:false},axisLine:{lineStyle:{color:'#dce4ee'}}},yAxis:{type:'value',splitLine:{lineStyle:{color:'#edf1f6',type:'dashed'}}},series:[{name:'签约金额',type:'bar',barWidth:18,data:salesTrend.signed.map(v=>Math.round(v*factor.value)),itemStyle:{borderRadius:[5,5,0,0]}},{name:'回款金额',type:'line',smooth:true,symbolSize:7,data:salesTrend.paid.map(v=>Math.round(v*factor.value)),lineStyle:{width:3}}]}))
const industryData=computed(()=>customerIndustries.map(name=>({name,value:scopedContracts.value.filter(c=>store.customerMap[c.customerId]?.industry===name).reduce((s,c)=>s+c.amount,0)})).filter(i=>i.value))
const industryOption=computed(()=>({color:['#246bfd','#35bfa7','#7667e8','#f0a13b','#6e89a9'],tooltip:{trigger:'item',formatter:'{b}<br/>{c} 万元 · {d}%'},legend:{bottom:0,itemWidth:9,itemHeight:9},series:[{type:'pie',radius:['44%','68%'],center:['50%','43%'],label:{show:false},data:industryData.value}]}))
const funnelStages=['初步接洽','需求确认','方案沟通','商务谈判','合同审批'],funnelOption=computed(()=>({color:['#7d6ce8'],tooltip:{trigger:'axis'},grid:{left:68,right:25,top:15,bottom:22},xAxis:{type:'value',splitLine:{lineStyle:{color:'#edf1f6',type:'dashed'}}},yAxis:{type:'category',data:[...funnelStages].reverse(),axisLine:{show:false},axisTick:{show:false}},series:[{type:'bar',barWidth:17,data:[...funnelStages].reverse().map(s=>scopedOpps.value.filter(i=>i.stage===s).reduce((n,i)=>n+i.amount,0)),itemStyle:{borderRadius:[0,6,6,0]}}]}))
function openMember(i){selectedMember.value=i;memberVisible.value=true}function exportAnalysis(){const rows=[['销售人员','签约金额','目标金额','客户数','赢单率'],...salesTeamPerformance.map(i=>[i.name,i.signed,i.target,i.customers,`${i.winRate}%`])];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([`\ufeff${rows.map(r=>r.join(',')).join('\n')}`],{type:'text/csv;charset=utf-8'}));a.download='销售分析.csv';a.click();URL.revokeObjectURL(a.href);ElMessage.success('销售分析已导出')}
</script>
<template><div class="sales-page analytics-page"><header class="sales-header analytics-header"><div><span>SALES ANALYTICS</span><h1>销售分析</h1><p>洞察签约、回款、客户结构与商机转化表现。</p></div><div class="analytics-filter-actions">
  <div class="analytics-filter-item"><span>统计周期</span><el-select v-model="period" aria-label="统计周期"><el-option label="本年度" value="year" /><el-option label="本季度" value="quarter" /><el-option label="本月" value="month" /></el-select></div>
  <div class="analytics-filter-item"><span>业务区域</span><el-select v-model="region" aria-label="业务区域"><el-option label="全部区域" value="all" /><el-option v-for="i in ['华东','华南','华北','西部']" :key="i" :label="i" :value="i" /></el-select></div>
  <div class="analytics-filter-item industry-filter"><span>客户行业</span><el-select v-model="industry" aria-label="客户行业"><el-option label="全部行业" value="all" /><el-option v-for="i in customerIndustries" :key="i" :label="i" :value="i" /></el-select></div>
  <el-button type="primary" @click="exportAnalysis"><el-icon><Download /></el-icon>导出分析</el-button>
</div></header>
<section class="analytics-hero"><div><span>销售签约金额</span><strong>{{totals.signed.toLocaleString()}}<small>万元</small></strong><em>较同期增长 14.3%</em></div><div><span>实际回款金额</span><strong>{{totals.paid.toLocaleString()}}<small>万元</small></strong><em>回款质量持续改善</em></div><div><span>客户资产</span><strong>{{totals.customers}}<small>家</small></strong><em>当前筛选范围</em></div><div><span>加权商机预测</span><strong>{{totals.forecast.toLocaleString()}}<small>万元</small></strong><em>按赢单概率计算</em></div></section>
<div class="analytics-grid"><section class="analytics-panel span-two"><header><div><h2>签约与回款趋势</h2><p>最近六个月销售产出</p></div><el-tag type="success">增长稳定</el-tag></header><BaseChart :option="trendOption" height="320px" /></section><section class="analytics-panel"><header><div><h2>行业收入结构</h2><p>合同金额贡献占比</p></div></header><BaseChart :option="industryOption" height="320px" /></section><section class="analytics-panel team-panel"><header><div><h2>销售团队业绩</h2><p>点击成员查看个人表现</p></div></header><button v-for="(i,index) in salesTeamPerformance" :key="i.name" @click="openMember(i)"><b>{{index+1}}</b><span><strong>{{i.name}}</strong><small>{{i.customers}} 家客户 · 赢单率 {{i.winRate}}%</small></span><div><em>{{i.signed}} 万</em><el-progress :percentage="Math.round(i.signed/i.target*100)" :stroke-width="5" :show-text="false" /></div></button></section><section class="analytics-panel"><header><div><h2>商机阶段金额</h2><p>销售漏斗健康度</p></div></header><BaseChart :option="funnelOption" height="290px" /></section><section class="analytics-panel forecast-panel"><header><div><h2>未来三个月预测</h2><p>基于预计签约日期与赢单概率</p></div></header><div class="forecast-bars"><div v-for="i in [{m:'10 月',v:386,p:78},{m:'11 月',v:298,p:60},{m:'12 月',v:246,p:49}]" :key="i.m"><span>{{i.m}}</span><div><i :style="{width:`${i.p}%`}"></i></div><strong>{{i.v}} 万</strong></div></div><aside><span>预测合计</span><strong>930 万元</strong><p>其中高意向商机贡献 62%</p></aside></section></div>
<el-drawer v-model="memberVisible" title="销售人员业绩" size="430px"><div v-if="selectedMember" class="member-detail"><el-avatar :size="62">{{selectedMember.name.slice(0,1)}}</el-avatar><h2>{{selectedMember.name}}</h2><p>销售管理中心</p><el-progress type="dashboard" :percentage="Math.round(selectedMember.signed/selectedMember.target*100)" /><el-descriptions :column="1" border><el-descriptions-item label="签约金额">{{selectedMember.signed}} 万元</el-descriptions-item><el-descriptions-item label="年度目标">{{selectedMember.target}} 万元</el-descriptions-item><el-descriptions-item label="负责客户">{{selectedMember.customers}} 家</el-descriptions-item><el-descriptions-item label="商机赢单率">{{selectedMember.winRate}}%</el-descriptions-item></el-descriptions></div></el-drawer></div></template>
