<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useProjectStore } from '../../stores/projects'

const route = useRoute()
const router = useRouter()
const store = useProjectStore()
const projectId = ref('all')
const status = ref('all')
const formVisible = ref(false)
const formRef = ref()
const mode = ref('create')
const form = reactive({ id: null, projectId: null, name: '', plannedDate: '', ownerId: null, deliverableText: '', acceptanceStatus: '待提交', isCustomerAcceptance: false })
const rules = { projectId: [{ required: true, message: '请选择项目', trigger: 'change' }], name: [{ required: true, message: '请输入里程碑名称', trigger: 'blur' }], plannedDate: [{ required: true, message: '请选择计划日期', trigger: 'change' }], ownerId: [{ required: true, message: '请选择负责人', trigger: 'change' }], deliverableText: [{ required: true, message: '请输入交付物', trigger: 'blur' }] }
const filtered = computed(() => store.milestones.filter((item) => !store.projectMap[item.projectId]?.archived && (projectId.value === 'all' || item.projectId === projectId.value) && (status.value === 'all' || item.acceptanceStatus === status.value)).sort((a, b) => a.plannedDate.localeCompare(b.plannedDate)))
const summary = computed(() => ({ total: filtered.value.length, passed: filtered.value.filter((item) => item.acceptanceStatus === '已通过').length, pending: filtered.value.filter((item) => item.acceptanceStatus === '待验收').length, rectifying: filtered.value.filter((item) => item.acceptanceStatus === '整改中').length }))

function reset() { Object.assign(form, { id: null, projectId: projectId.value === 'all' ? null : projectId.value, name: '', plannedDate: '', ownerId: null, deliverableText: '', acceptanceStatus: '待提交', isCustomerAcceptance: false }) }
function openCreate() { reset(); mode.value = 'create'; formVisible.value = true }
function openEdit(item) { Object.assign(form, { ...item, deliverableText: item.deliverables.join('、') }); mode.value = 'edit'; formVisible.value = true }
async function save() { await formRef.value.validate(); const payload = { ...form, deliverables: form.deliverableText.split(/[、,，]/).map((item) => item.trim()).filter(Boolean) }; delete payload.id; delete payload.deliverableText; mode.value === 'create' ? store.addMilestone(payload) : store.updateMilestone(form.id, payload); formVisible.value = false; ElMessage.success(mode.value === 'create' ? '里程碑已创建' : '里程碑已更新') }
async function remove(item) { try { await ElMessageBox.confirm(`确定删除里程碑“${item.name}”吗？`, '删除里程碑', { confirmButtonText: '确定删除', cancelButtonText: '取消', type: 'warning' }); store.removeMilestone(item.id); ElMessage.success('里程碑已删除') } catch { /* 保留里程碑。 */ } }
async function approve(item) { try { await ElMessageBox.confirm(item.isCustomerAcceptance ? '通过后将触发验收款到期，并把合同调整为待结算。确定继续吗？' : `确认“${item.name}”验收通过吗？`, '验收确认', { confirmButtonText: '确认通过', cancelButtonText: '取消', type: 'warning' }); store.approveMilestone(item.id); ElMessage.success(item.isCustomerAcceptance ? '客户验收、合同和回款计划已同步' : '里程碑已验收通过') } catch { /* 保持状态。 */ } }
async function returnItem(item) { try { const { value } = await ElMessageBox.prompt('请填写整改要求', '退回整改', { confirmButtonText: '确认退回', cancelButtonText: '取消', inputValidator: (input) => Boolean(input?.trim()) || '请填写整改要求' }); store.returnMilestone(item.id, value); ElMessage.success('已退回整改') } catch { /* 保持状态。 */ } }
function statusType(value) { return { 已通过: 'success', 待验收: 'warning', 整改中: 'danger', 进行中: 'primary', 待提交: 'info' }[value] || 'info' }
onMounted(() => { if (route.query.projectId) projectId.value = Number(route.query.projectId) })
</script>

<template>
  <div class="project-page milestone-page">
    <header class="project-header"><div><span>DELIVERY MILESTONES</span><h1>里程碑管理</h1><p>跟踪关键交付节点、交付物和客户验收状态。</p></div><el-button type="primary" @click="openCreate"><el-icon><Plus /></el-icon>新建里程碑</el-button></header>
    <section class="milestone-control"><div><span>全部节点</span><strong>{{ summary.total }}</strong></div><div><span>已通过</span><strong>{{ summary.passed }}</strong></div><div><span>待验收</span><strong>{{ summary.pending }}</strong></div><div class="danger"><span>整改中</span><strong>{{ summary.rectifying }}</strong></div><aside><el-select v-model="projectId"><el-option label="全部项目" value="all" /><el-option v-for="item in store.activeProjects" :key="item.id" :label="item.name" :value="item.id" /></el-select><el-select v-model="status"><el-option label="全部状态" value="all" /><el-option v-for="item in ['待提交','进行中','待验收','整改中','已通过']" :key="item" :label="item" :value="item" /></el-select></aside></section>
    <section class="milestone-roadmap"><header><h2>交付时间轴</h2><p>点击节点可进入对应项目详情</p></header><div class="roadmap-line"><article v-for="(item, index) in filtered" :key="item.id" :class="{ passed: item.acceptanceStatus === '已通过', danger: item.acceptanceStatus === '整改中' }"><div class="roadmap-date">{{ item.plannedDate }}</div><button @click="router.push(`/projects/${item.projectId}`)"><i>{{ index + 1 }}</i><strong>{{ item.name }}</strong><span>{{ store.projectMap[item.projectId]?.name }}</span><el-tag :type="statusType(item.acceptanceStatus)" size="small">{{ item.acceptanceStatus }}</el-tag></button></article></div><el-empty v-if="!filtered.length" description="没有符合条件的里程碑" /></section>
    <section class="milestone-ledger"><header><div><h2>里程碑明细</h2><p>交付、提交、验收和整改全过程</p></div></header><el-table :data="filtered"><el-table-column label="里程碑" min-width="190"><template #default="{ row }"><strong>{{ row.name }}</strong><el-tag v-if="row.isCustomerAcceptance" size="small" type="primary">客户验收</el-tag></template></el-table-column><el-table-column label="所属项目" min-width="180"><template #default="{ row }">{{ store.projectMap[row.projectId]?.name }}</template></el-table-column><el-table-column prop="plannedDate" label="计划日期" width="110" /><el-table-column prop="actualDate" label="实际日期" width="110"><template #default="{ row }">{{ row.actualDate || '—' }}</template></el-table-column><el-table-column label="负责人" width="90"><template #default="{ row }">{{ store.employeeMap[row.ownerId]?.name }}</template></el-table-column><el-table-column label="交付物" min-width="150"><template #default="{ row }">{{ row.deliverables.join('、') }}</template></el-table-column><el-table-column label="验收状态" width="100"><template #default="{ row }"><el-tag :type="statusType(row.acceptanceStatus)">{{ row.acceptanceStatus }}</el-tag></template></el-table-column><el-table-column label="操作" width="230" fixed="right"><template #default="{ row }"><el-button v-if="row.acceptanceStatus === '待提交'" link type="primary" @click="store.submitMilestone(row.id)">提交</el-button><template v-if="row.acceptanceStatus === '待验收'"><el-button link type="success" @click="approve(row)">通过</el-button><el-button link type="warning" @click="returnItem(row)">退回</el-button></template><el-button link @click="openEdit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table></section>
    <el-dialog v-model="formVisible" :title="mode === 'create' ? '新建交付里程碑' : '编辑交付里程碑'" width="680px"><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><div class="project-form-grid"><el-form-item label="所属项目" prop="projectId"><el-select v-model="form.projectId" filterable style="width:100%"><el-option v-for="item in store.activeProjects" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item><el-form-item label="负责人" prop="ownerId"><el-select v-model="form.ownerId" style="width:100%"><el-option v-for="item in store.deliveryEmployees" :key="item.id" :label="`${item.name} · ${item.position}`" :value="item.id" /></el-select></el-form-item><el-form-item label="里程碑名称" prop="name"><el-input v-model="form.name" /></el-form-item><el-form-item label="计划日期" prop="plannedDate"><el-date-picker v-model="form.plannedDate" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item><el-form-item label="验收状态"><el-select v-model="form.acceptanceStatus" style="width:100%"><el-option v-for="item in ['待提交','进行中','待验收','整改中']" :key="item" :label="item" :value="item" /></el-select></el-form-item><el-form-item label="客户最终验收"><el-switch v-model="form.isCustomerAcceptance" active-text="通过后联动合同结算" /></el-form-item><el-form-item label="交付物" prop="deliverableText" class="span-two"><el-input v-model="form.deliverableText" placeholder="多个交付物使用顿号分隔" /></el-form-item></div></el-form><template #footer><el-button @click="formVisible = false">取消</el-button><el-button type="primary" @click="save">保存里程碑</el-button></template></el-dialog>
  </div>
</template>
